import {JetBrains_Mono} from "next/font/google"
import "./globals.css";

//components
import { PageTransition } from "../components/PageTransition";
import {Header} from "../components/Header"
import { StairTransition } from "@/components/StairTransition";

const jetBrainsMono = JetBrains_Mono({ 
  subsets: ["latin"], 
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: '--font-jetbrainsMono'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body
        className={jetBrainsMono.variable}
      >
        <Header />
        <PageTransition>
          <StairTransition />
          {children}
        </PageTransition>
      </body>
    </html>
  );
}
